#!/bin/bash

#
# (C) 2010-2012 - Auke Kok <auke@foo-projects.org>
#

# This file is part of Album.
#
#   Album is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Affero General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   Album is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU Affero General Public License
#   along with Album.  If not, see <http://www.gnu.org/licenses/>.

export PATH=/bin:/usr/bin:/sbin:/usr/sbin

export IFS=$'\n '

inotifywait -e close_write -e create -r -m --format "%e %w%f" /home/*/album | while read EVENT FILE ; do
	if [ "$EVENT" == "CREATE,ISDIR" ]; then
		systemctl restart album-watch.service &
		exit 0
	fi
	if [ "$EVENT" != "CLOSE_WRITE,CLOSE" -o ! -f "$FILE" ]; then
		continue
	fi
	if echo "$FILE" | grep -q -e '[.]\(avi\|AVI\|mpg\|MPG\|ogv\|OGV\|mp4\|MP4\)$' ; then
		BASE=$(echo "$FILE" | sed 's/[.]\([a-zA-Z0-9]*\)$//')
		if [ $? != 0 ]; then
			continue
		fi
		OWNER=$(stat --format=%U "$FILE")
		if [ $? != 0 ]; then
			continue
		fi
		if [ ! -f "$BASE.thm" ]; then
			echo "$0: generating $BASE.thm"
			sudo -u $OWNER ffmpeg -i "$FILE" -ss 0 -vframes 1 -f mjpeg -an "$BASE.thm.in" > /dev/null 2>&1
			sudo -u $OWNER convert "$BASE.thm.in" -resize 100x100 "$BASE.thm" > /dev/null 2>&1
			sudo -u $OWNER rm "$BASE.thm.in" > /dev/null 2>&1
			sleep 1
		fi
		if [ ! -f "$BASE.mp4" ]; then
			echo "$0: generating $BASE.mp4"
			sudo -u $OWNER ffmpeg -i "$FILE" -vcodec libx264 "$BASE.mp4" > /dev/null 2>&1
			sleep 1
		fi
		if [ ! -f "$BASE.ogv" ]; then
			echo "$0: generating $BASE.ogv"
			sudo -u $OWNER ffmpeg2theora "$BASE.mp4" -o "$BASE.ogv" > /dev/null 2>&1
			sleep 1
		fi
	fi
done

